name: 定时更新汇率
on:
  schedule:
    # 北京时间 每日早上8点自动运行
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 拉取仓库完整代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 配置 Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装axios依赖
        run: npm install axios --save

      - name: 运行汇率更新脚本
        run: node updateRate.js

      - name: 提交并推送更新
        run: |
          git config --global user.name "Auto-RateBot"
          git config --global user.email "bot@github.com"
          git add index.html
          git diff --quiet && git diff --staged --quiet || (git commit -m "【自动任务】更新UAH-CNY实时汇率" && git push)
